### ISSUE TITLE
Handler not defined

### ISSUE THREAD

**Issue by dasmochael** [manojlds/ebs-snapshot-lambda#1]
I am not able to find where the handler is defined.  I have tried many variations, but with failure.  Can you please add to the Read Me the defined handler?

**Comment by manojlds** [comment]
The handler is defined here - https://github.com/manojlds/ebs-snapshot-lambda/blob/master/lambda/ebs_snapshot_lambda.js#L17

**Comment by dasmochael** [comment]
So when this is created in lambda, i set the handler to exports.handler?  I get this error when i do that:
`  "errorMessage": "Cannot find module '/var/task/exports'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:417:25)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)"
  ]`

**Comment by dasmochael** [comment]
Sorry - it was my mistake.  The zip contained an extra dir that was messing it up.
